name: 'Changed Filenames'
description: 'GitHub Action to fetch changed filenames in pull pequests.'
author: 'DawChihLiou'

branding:
  icon: "file-plus"  
  color: "black"
  
runs:
  using: 'node12'
  main: 'dist/index.js'
  
inputs:
  token:
    required: true
    description: |
      GitHub API token.
      Default to "secrets.GITHUB_TOKEN".
    default: ${{ github.token }}
  output:
    required: true
    decription: |
      Output format: "string" or "json".
      If the `output` is set to "string", you will recieve a string of filenames with " " in between each filename.
      If the `output` is set to "json", you will recieve an array of filenames in JSON.
      Default to "string".
    default: string
outputs:
  filenames:
    description: |
      All changed filenames, including added, modified, renamed, and removed files.
